networks:
  testcontainers-network:
    driver: bridge

services:
  postgres:
    image: 'postgres:14'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    networks:
      - testcontainers-network

  settlements-enrichment-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: settlements-enrichment-service
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - testcontainers-network

  tests:
    image: maven:3
    stop_signal: SIGKILL
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      # Maven cache (optional)
      - ~/.m2:/root/.m2
    command: mvn test
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
    networks:
      - testcontainers-network
